In [2]:
import pandas as pd
import numpy as np
import math

In [3]:
df=pd.read_excel('titanic3.xlsx')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   pclass     1309 non-null   int64  
 1   survived   1309 non-null   int64  
 2   name       1309 non-null   object 
 3   sex        1309 non-null   object 
 4   age        1046 non-null   float64
 5   sibsp      1309 non-null   int64  
 6   parch      1309 non-null   int64  
 7   ticket     1309 non-null   object 
 8   fare       1308 non-null   float64
 9   cabin      295 non-null    object 
 10  embarked   1307 non-null   object 
 11  boat       486 non-null    object 
 12  body       121 non-null    float64
 13  home.dest  745 non-null    object 
dtypes: float64(3), int64(4), object(7)
memory usage: 143.3+ KB


In [5]:
df.dtypes

pclass         int64
survived       int64
name          object
sex           object
age          float64
sibsp          int64
parch          int64
ticket        object
fare         float64
cabin         object
embarked      object
boat          object
body         float64
home.dest     object
dtype: object

In [6]:
df.describe()

pclass     survived          age        sibsp        parch  \
count  1309.000000  1309.000000  1046.000000  1309.000000  1309.000000   
mean      2.294882     0.381971    29.881135     0.498854     0.385027   
std       0.837836     0.486055    14.413500     1.041658     0.865560   
min       1.000000     0.000000     0.166700     0.000000     0.000000   
25%       2.000000     0.000000    21.000000     0.000000     0.000000   
50%       3.000000     0.000000    28.000000     0.000000     0.000000   
75%       3.000000     1.000000    39.000000     1.000000     0.000000   
max       3.000000     1.000000    80.000000     8.000000     9.000000   

              fare        body  
count  1308.000000  121.000000  
mean     33.295479  160.809917  
std      51.758668   97.696922  
min       0.000000    1.000000  
25%       7.895800   72.000000  
50%      14.454200  155.000000  
75%      31.275000  256.000000  
max     512.329200  328.000000

In [7]:
df["survived"].value_counts()

survived
0    809
1    500
Name: count, dtype: int64

In [8]:
print("A quantidade de sobreviventes é:", df["survived"].sum())
print("A quantidade de não sobreviventes é:", (df['survived']==0).sum())

A quantidade de sobreviventes é: 500
A quantidade de não sobreviventes é: 809


In [9]:
print("No titanic, {} pessoas sobreviveram e {} pessoas morreram." .format(df["survived"].sum(), (df['survived']==0).sum()) )

No titanic, 500 pessoas sobreviveram e 809 pessoas morreram.


In [10]:
print("No titanic, dos {} passageiros, {} eram homens e {} eram mulheres." .format(len(df), len(df[df["sex"]=="male"]), len(df[df["sex"]=="female"])))

No titanic, dos 1309 passageiros, 843 eram homens e 466 eram mulheres.


In [11]:
df['age'] = df['age'].round().astype('Int64')

In [12]:
int(df['age'].mean())


29

In [13]:
df['pclass'].value_counts()

pclass
3    709
1    323
2    277
Name: count, dtype: int64

In [14]:
print("Do titanic, {} pessoas estavam na primeira classe, {} pessoas na segunda classe e {} pessoas na terceira classe." .format(df['pclass'].value_counts()[1], df['pclass'].value_counts()[2], df['pclass'].value_counts()[3])    )

Do titanic, 323 pessoas estavam na primeira classe, 277 pessoas na segunda classe e 709 pessoas na terceira classe.


In [15]:
df2 = df.copy()

In [32]:
df.describe()

pclass     survived        age        sibsp        parch  \
count  1309.000000  1309.000000     1046.0  1309.000000  1309.000000   
mean      2.294882     0.381971  29.870937     0.498854     0.385027   
std       0.837836     0.486055  14.411571     1.041658     0.865560   
min       1.000000     0.000000        0.0     0.000000     0.000000   
25%       2.000000     0.000000       21.0     0.000000     0.000000   
50%       3.000000     0.000000       28.0     0.000000     0.000000   
75%       3.000000     1.000000       39.0     1.000000     0.000000   
max       3.000000     1.000000       80.0     8.000000     9.000000   

              fare        body  
count  1308.000000  121.000000  
mean     33.295479  160.809917  
std      51.758668   97.696922  
min       0.000000    1.000000  
25%       7.895800   72.000000  
50%      14.454200  155.000000  
75%      31.275000  256.000000  
max     512.329200  328.000000

In [33]:
df2['age'] = df2['age'].fillna(29)
df2.isnull().sum()

pclass          0
survived        0
name            0
sex             0
age             0
sibsp           0
parch           0
ticket          0
fare            1
cabin           0
embarked        0
boat          823
body         1188
home.dest     564
dtype: int64

In [17]:
df2.embarked.value_counts()


embarked
S    914
C    270
Q    123
Name: count, dtype: int64

In [18]:
embarked = df2['embarked'].dropna()


In [19]:
df2[df2['embarked'].isnull()]


pclass  survived                                       name     sex  age  \
168       1         1                        Icard, Miss. Amelie  female   38   
284       1         1  Stone, Mrs. George Nelson (Martha Evelyn)  female   62   

     sibsp  parch  ticket  fare cabin embarked boat  body       home.dest  
168      0      0  113572  80.0   B28      NaN    6   NaN             NaN  
284      0      0  113572  80.0   B28      NaN    6   NaN  Cincinatti, OH

In [20]:
df2['embarked'].mode()

0    S
Name: embarked, dtype: object

In [ ]:
#df2["embarked"].fillna(df2['embarked'].mode()[0], inplace=True)

C:\Users\ResTIC16\AppData\Local\Temp\ipykernel_29492\3046757764.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df2["embarked"].fillna(df2['embarked'].mode()[0], inplace=True)


In [44]:
df2['fare'] = df2['fare'].round().astype('Int64')

In [22]:
df2.isnull().sum()

pclass          0
survived        0
name            0
sex             0
age             0
sibsp           0
parch           0
ticket          0
fare            1
cabin        1014
embarked        0
boat          823
body         1188
home.dest     564
dtype: int64

In [43]:
df2.dtypes

pclass        int64
survived      int64
name          int16
sex           int64
age           Int64
sibsp         int64
parch         int64
ticket       object
fare        float64
cabin        object
embarked     object
dtype: object

In [23]:
df2['cabin'].mode()

0    C23 C25 C27
Name: cabin, dtype: object

In [ ]:
#df2['cabin'].fillna(df2['cabin'].mode()[0], inplace=True)

C:\Users\ResTIC16\AppData\Local\Temp\ipykernel_29492\1439731185.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df2['cabin'].fillna(df2['cabin'].mode()[0], inplace=True)


In [45]:
df2.isnull().sum()


pclass      0
survived    0
name        0
sex         0
age         0
sibsp       0
parch       0
ticket      0
fare        0
cabin       0
embarked    0
dtype: int64

In [39]:
df2.drop(['boat','body','home.dest'], axis=1, inplace=True)

In [ ]:
df2['fare'].fillna(int(df2['fare'].mean()), inplace=True)

In [28]:
df2['name'] = df2['name'].astype('category').cat.codes

In [30]:
df2['sex'] = df2['sex'].apply(lambda x: 1 if x == 'male' else 0)

In [31]:
display(df2)

pclass  survived  name  sex  age  sibsp  parch  ticket      fare  \
0          1         1    21    0   29      0      0   24160  211.3375   
1          1         1    23    1    1      1      2  113781  151.5500   
2          1         0    24    0    2      1      2  113781  151.5500   
3          1         0    25    1   30      1      2  113781  151.5500   
4          1         0    26    0   25      1      2  113781  151.5500   
...      ...       ...   ...  ...  ...    ...    ...     ...       ...   
1304       3         0  1291    0   14      1      0    2665   14.4542   
1305       3         0  1292    0   29      1      0    2665   14.4542   
1306       3         0  1293    1   26      0      0    2656    7.2250   
1307       3         0  1294    1   27      0      0    2670    7.2250   
1308       3         0  1295    1   29      0      0  315082    7.8750   

            cabin embarked boat   body                        home.dest  
0              B5        S    2    NaN                     St Louis, MO  
1         C22 C26        S   11    NaN  Montreal, PQ / Chesterville, ON  
2         C22 C26        S  NaN    NaN  Montreal, PQ / Chesterville, ON  
3         C22 C26        S  NaN  135.0  Montreal, PQ / Chesterville, ON  
4         C22 C26        S  NaN    NaN  Montreal, PQ / Chesterville, ON  
...           ...      ...  ...    ...                              ...  
1304  C23 C25 C27        C  NaN  328.0                              NaN  
1305  C23 C25 C27        C  NaN    NaN                              NaN  
1306  C23 C25 C27        C  NaN  304.0                              NaN  
1307  C23 C25 C27        C  NaN    NaN                              NaN  
1308  C23 C25 C27        S  NaN    NaN                              NaN  

[1309 rows x 14 columns]

In [46]:
df2.corr(numeric_only=True)

pclass  survived      name       sex       age     sibsp  \
pclass    1.000000 -0.312469  0.048207  0.124617 -0.372376  0.060832   
survived -0.312469  1.000000 -0.032298 -0.528693 -0.046747 -0.027825   
name      0.048207 -0.032298  1.000000  0.036812  0.028796 -0.000070   
sex       0.124617 -0.528693  0.036812  1.000000  0.055405 -0.109609   
age      -0.372376 -0.046747  0.028796  0.055405  1.000000 -0.190374   
sibsp     0.060832 -0.027825 -0.000070 -0.109609 -0.190374  1.000000   
parch     0.018322  0.082660 -0.035679 -0.213125 -0.128435  0.373587   
fare     -0.558526  0.244013 -0.037428 -0.185371  0.175196  0.160396   

             parch      fare  
pclass    0.018322 -0.558526  
survived  0.082660  0.244013  
name     -0.035679 -0.037428  
sex      -0.213125 -0.185371  
age      -0.128435  0.175196  
sibsp     0.373587  0.160396  
parch     1.000000  0.221239  
fare      0.221239  1.000000

In [47]:
df2.to_excel('titanic_limpo.xlsx', index=False)

In [59]:
x = df2[['pclass', 'survived', 'name', 'sex', 'age', 'sibsp', 'parch', 'fare']]

In [60]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split


In [61]:
model = LogisticRegression()

In [62]:
x_train, x_test, y_train, y_test = train_test_split(x.drop('survived', axis=1), x['survived'], test_size=0.3, random_state=42)

In [63]:
x_train

pclass  name  sex  age  sibsp  parch  fare
1214       3  1113    1   29      0      0     9
677        3   135    1   26      0      0     8
534        2   965    0   19      0      0    26
1174       3  1051    0   29      8      2    70
864        3   527    0   28      0      0     8
...      ...   ...  ...  ...    ...    ...   ...
1095       3   888    0   29      0      0     8
1130       3   962    0   18      0      0     8
1294       3  1273    1   28      0      0    16
860        3   523    0   26      0      0     8
1126       3   958    0   28      0      0     8

[916 rows x 7 columns]

In [64]:
y_train

1214    0
677     0
534     1
1174    0
864     0
       ..
1095    0
1130    0
1294    0
860     1
1126    0
Name: survived, Length: 916, dtype: int64

In [66]:
model.fit(x_train, y_train)

c:\Users\ResTIC16\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [68]:
predictions = model.predict(x_test)
predictions

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,

In [70]:
from sklearn.metrics import classification_report, confusion_matrix

In [71]:
print(confusion_matrix(y_test, predictions))

[[204  20]
 [ 57 112]]


In [72]:
print(confusion_matrix(y_test, predictions))

[[204  20]
 [ 57 112]]


In [78]:
manu = {'pclass': 3,
        'name': 1245,
        'sex': 0,
        'age': 23,
        'sibsp': 2,
        'parch': 0,
        'fare': 120
}
manu_df = pd.DataFrame([manu])
manu_df

pclass  name  sex  age  sibsp  parch  fare
0       3  1245    0   23      2      0   120

In [79]:
model.predict(manu_df)

array([1])